platform :ios


target 'TestWaxPod' do
	platform:ios, '6.0'
	#pod 'wax', :git=>'https://github.com/alibaba/wax.git', :tag=>'1.1.0'
    #pod 'wax', :git=>'https://github.com/alibaba/wax.git', :commit=>'5c762ad'
    pod 'wax', :path=>'../../../'
end
