#!/usr/bin/env zsh

# This script will create a new xcode project!

project_template="/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Project Templates/Application/Window-based Application/Window-based Application"
project_name=$1
user_fullname=$( id -P "$( whoami )" | cut -d ':' -f 8 )

if [[ -z $project_name ]]; then
	echo "ERROR: No project name given."
	exit 1
fi

project_name_as_identifier=$( echo $project_name | sed "s/[^\-_0-9a-zA-Z]//g" )

if [[ -z $output_dir ]]; then
	output_dir=$project_name
else
	output_dir="$2/$project_name"
fi

if [[ -e $output_dir ]]; then
	echo "ERROR: Path '$output_dir' already exists!"
	exit 1
fi

mkdir -p "$output_dir"
cp -R "$project_template"/* "$output_dir"

# Change the template strings in the filename
for file in "$output_dir"/**/*___*___*; do
	if [[ $file == *_PROJECTNAMEASIDENTIFIER_* ]]; then	
		new_file=$( echo $file | sed "s/___[^_]*___/$project_name_as_identifier/g" ) 
	elif [[ $file == *_PROJECTNAME_* ]]; then
		new_file=$( echo $file | sed "s/___[^_]*___/$project_name/g" ) 
	else
		echo "ERROR: Unknown template file for '$file'"
		exit 1
	fi
	
	mv "$file" "$new_file"
done

# Change the template strings in the file
grep -rl '___.*___' "$output_dir" | while read file; do
	sed -i "" -e "s/___PROJECTNAMEASIDENTIFIER___/$project_name_as_identifier/g" "$file"
	sed -i "" -e "s/___PROJECTNAME___/$project_name/g" "$file"
	sed -i "" -e "s/___YEAR___/$(date "+%Y")/g" "$file"
	sed -i "" -e "s/___FULLUSERNAME___/$user_fullname/g" "$file"
	sed -i "" -e "s/___DATE___/$(date "+%B %d +Y")/g" "$file"	
done